// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProEventos.Api.Data;

namespace ProEventos.Api.Data.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20220206225044_Atualizando_a_tabela_Eventos")]
    partial class Atualizando_a_tabela_Eventos
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.13");

            modelBuilder.Entity("ProEventos.Api.Models.Evento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CreateAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DataEvento")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImagemURL")
                        .HasColumnType("TEXT");

                    b.Property<string>("Local")
                        .HasColumnType("TEXT");

                    b.Property<int>("QtdPessoas")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Telefone")
                        .HasColumnType("TEXT");

                    b.Property<string>("Tema")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdateAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Eventos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreateAt = new DateTime(2022, 8, 22, 2, 8, 3, 197, DateTimeKind.Local).AddTicks(9950),
                            DataEvento = new DateTime(2022, 6, 17, 18, 35, 34, 104, DateTimeKind.Local).AddTicks(6064),
                            Email = "Jennifer9@gmail.com",
                            ImagemURL = "data:image/svg+xml;charset=UTF-8,%3Csvg%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20version%3D%221.1%22%20baseProfile%3D%22full%22%20width%3D%22150%22%20height%3D%22200%22%3E%3Crect%20width%3D%22100%25%22%20height%3D%22100%25%22%20fill%3D%22grey%22%2F%3E%3Ctext%20x%3D%2275%22%20y%3D%22100%22%20font-size%3D%2220%22%20alignment-baseline%3D%22middle%22%20text-anchor%3D%22middle%22%20fill%3D%22white%22%3E150x200%3C%2Ftext%3E%3C%2Fsvg%3E",
                            Local = "Ricky Williamson",
                            QtdPessoas = 75,
                            Telefone = "357-270-9332 x15350",
                            Tema = "Olson LLC"
                        },
                        new
                        {
                            Id = 3,
                            CreateAt = new DateTime(2022, 9, 3, 1, 59, 19, 104, DateTimeKind.Local).AddTicks(2484),
                            DataEvento = new DateTime(2022, 5, 15, 0, 41, 49, 381, DateTimeKind.Local).AddTicks(9397),
                            Email = "Jared_Williamson45@yahoo.com",
                            ImagemURL = "data:image/svg+xml;charset=UTF-8,%3Csvg%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20version%3D%221.1%22%20baseProfile%3D%22full%22%20width%3D%22150%22%20height%3D%22200%22%3E%3Crect%20width%3D%22100%25%22%20height%3D%22100%25%22%20fill%3D%22grey%22%2F%3E%3Ctext%20x%3D%2275%22%20y%3D%22100%22%20font-size%3D%2220%22%20alignment-baseline%3D%22middle%22%20text-anchor%3D%22middle%22%20fill%3D%22white%22%3E150x200%3C%2Ftext%3E%3C%2Fsvg%3E",
                            Local = "Tyrique Johnson",
                            QtdPessoas = 2,
                            Telefone = "(583) 565-6511",
                            Tema = "Bernhard, Kuhlman and Waters"
                        },
                        new
                        {
                            Id = 5,
                            CreateAt = new DateTime(2022, 11, 7, 2, 10, 30, 675, DateTimeKind.Local).AddTicks(8770),
                            DataEvento = new DateTime(2022, 4, 5, 3, 41, 20, 265, DateTimeKind.Local).AddTicks(4063),
                            Email = "Spencer_Ernser33@yahoo.com",
                            ImagemURL = "data:image/svg+xml;charset=UTF-8,%3Csvg%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20version%3D%221.1%22%20baseProfile%3D%22full%22%20width%3D%22150%22%20height%3D%22200%22%3E%3Crect%20width%3D%22100%25%22%20height%3D%22100%25%22%20fill%3D%22grey%22%2F%3E%3Ctext%20x%3D%2275%22%20y%3D%22100%22%20font-size%3D%2220%22%20alignment-baseline%3D%22middle%22%20text-anchor%3D%22middle%22%20fill%3D%22white%22%3E150x200%3C%2Ftext%3E%3C%2Fsvg%3E",
                            Local = "Beulah Bauch",
                            QtdPessoas = 28,
                            Telefone = "876-351-5030 x064",
                            Tema = "Schinner - Grady"
                        },
                        new
                        {
                            Id = 7,
                            CreateAt = new DateTime(2022, 10, 11, 8, 59, 24, 209, DateTimeKind.Local).AddTicks(4104),
                            DataEvento = new DateTime(2022, 10, 9, 6, 0, 13, 937, DateTimeKind.Local).AddTicks(1747),
                            Email = "Rolando_Bayer36@yahoo.com",
                            ImagemURL = "data:image/svg+xml;charset=UTF-8,%3Csvg%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20version%3D%221.1%22%20baseProfile%3D%22full%22%20width%3D%22150%22%20height%3D%22200%22%3E%3Crect%20width%3D%22100%25%22%20height%3D%22100%25%22%20fill%3D%22grey%22%2F%3E%3Ctext%20x%3D%2275%22%20y%3D%22100%22%20font-size%3D%2220%22%20alignment-baseline%3D%22middle%22%20text-anchor%3D%22middle%22%20fill%3D%22white%22%3E150x200%3C%2Ftext%3E%3C%2Fsvg%3E",
                            Local = "Laney Hyatt",
                            QtdPessoas = 87,
                            Telefone = "837-631-4263",
                            Tema = "Steuber and Sons"
                        },
                        new
                        {
                            Id = 9,
                            CreateAt = new DateTime(2023, 1, 10, 1, 44, 3, 900, DateTimeKind.Local).AddTicks(5857),
                            DataEvento = new DateTime(2022, 10, 3, 21, 59, 5, 456, DateTimeKind.Local).AddTicks(186),
                            Email = "Meredith.Bradtke@gmail.com",
                            ImagemURL = "data:image/svg+xml;charset=UTF-8,%3Csvg%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20version%3D%221.1%22%20baseProfile%3D%22full%22%20width%3D%22150%22%20height%3D%22200%22%3E%3Crect%20width%3D%22100%25%22%20height%3D%22100%25%22%20fill%3D%22grey%22%2F%3E%3Ctext%20x%3D%2275%22%20y%3D%22100%22%20font-size%3D%2220%22%20alignment-baseline%3D%22middle%22%20text-anchor%3D%22middle%22%20fill%3D%22white%22%3E150x200%3C%2Ftext%3E%3C%2Fsvg%3E",
                            Local = "Horacio Reichert",
                            QtdPessoas = 82,
                            Telefone = "651-634-6952 x083",
                            Tema = "Erdman, Kohler and Mohr"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
